baseURL = "https://robug.deaves.net"
locale = "en-us"
title = "RoBug Build Log"
theme = "hyde"
paginate = 10

[params]
  author = "Michael Deaves"
  description = "Documenting the build of a smart electric utility rover."

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
